# Questions

## libraries

In [26]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg 

## Lineal Algebra

**1)What is broadcasting in connection to Linear Algebra?** 

This has a relationship with numpy and that describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [4]:
M = np.array([[1, 6, 2],
              [4, 2, 3],
              [1, 4, 2]])

v = np.array([5, 2, 1])

print(M + v)

[[6 8 3]
 [9 4 4]
 [6 6 3]]


**2)What are scalars, vectors, matrices, and tensors?**

**Scalars**:Is a current number like Reals $R$, Integers $Z$ and Naturals $N$, in python they are present like float, complex, bytes to just scalars numbers.
**Vectors**:Is a set of scalars in a array, these are dennoted by a small letter.
**Matrices**:Is a array bi-dimensional numbers and have two index  for row and columns. This is represented with a capital letter.
**Tensors**:Is a set of matrices with more ejes that represent as cub or a image RGB (each channel color), have three dimensions (n,m,p), row, columns and deep respectively. 

In [5]:
'''Scalars Numbers'''
a = 2
b = 4.8
c = 7.435

print(a)
print(b)
print(c)

2
4.8
7.435


In [6]:
'''Vectors'''
a=np.array([2,5,7,9,10])
print(a)

[ 2  5  7  9 10]


In [8]:
'''Matrices'''
M=np.array([[2,5,7,8],[23,5,6,7],[34,4,5,4]])
print(M)

[[ 2  5  7  8]
 [23  5  6  7]
 [34  4  5  4]]


In [15]:
'''Tensors'''
T = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


**3) What is Hadamard product of two matrices?** 
Is a multiplication with the same dimentions between two matrices. It is often 
confused with normal multiplication.

In [22]:
'''Hadamard product'''
A=np.array([[2,3,4,5],[2,3,4,6],[6,46,4,3]])
B=np.array([[2,3,4,5],[2,3,4,6],[6,6,4,3]])
print(np.multiply(A,B))

[[  4   9  16  25]
 [  4   9  16  36]
 [ 36 276  16   9]]


**4) What is an inverse matrix?**
Also called Invertible Matrix, nonsingular or nondegenerate,  if there exists an n-by-n square matrix B such that

    AB = BA = I_n

where In denotes the n-by-n identity matrix and the multiplication used is ordinary matrix multiplication. If this is the case, then the matrix B is uniquely determined by A and is called the inverse of A, denoted by A−1.

A square matrix that is not invertible is called singular or degenerate. A square matrix is singular if and only if its determinant is 0. Singular matrices are rare in the sense that a square matrix randomly selected from a continuous uniform distribution on its entries will almost never be singular. 

In [28]:
'''Invertible Matrix'''
A=np.array([[2,3,5],[2,3,4],[6,4,3]])
print(np.linalg.inv(A))

[[ 0.7 -1.1  0.3]
 [-1.8  2.4 -0.2]
 [ 1.  -1.   0. ]]


**5) If inverse of a matrix exists, how to calculate it?**
There are 3 way to resolve the inverse of the matrix.
 - Aplicate the definition and  solve equations respectively.
 - Using Gauss Method.
 - Using Determinants and atachments.

Here there is a way to solve:
http://recursostic.educacion.es/descartes/web/materiales_didacticos/matrices/inversa_de_una_matriz.htm

**6) What is the determinant of a square matrix? How is it calculated? What is the connection of determinant to eigenvalues?**


In [29]:
'''Determinant'''
A=np.array([[2,3,5],[2,3,4],[6,4,3]])
print(np.linalg.det(A))

-10.0


In [ ]:

Discuss span and linear dependence.
What is Ax = b? When does Ax =b has a unique solution?
In Ax = b, what happens when A is fat or tall?
When does inverse of A exist?
What is a norm? What is L1, L2 and L infinity norm?
What are the conditions a norm has to satisfy?
Why is squared of L2 norm preferred in ML than just L2 norm?
When L1 norm is preferred over L2 norm?
Can the number of nonzero elements in a vector be defined as L0 norm? If no, why?
What is Frobenius norm?
What is a diagonal matrix?
Why is multiplication by diagonal matrix computationally cheap? How is the multiplication different for square vs. non-square diagonal matrix?
At what conditions does the inverse of a diagonal matrix exist?
What is a symmetrix matrix?
What is a unit vector?
When are two vectors x and y orthogonal?
At R^n what is the maximum possible number of orthogonal vectors with non-zero norm?
When are two vectors x and y orthonormal?
What is an orthogonal matrix? Why is computationally preferred?
What is eigendecomposition, eigenvectors and eigenvalues?
How to find eigen values of a matrix?
Write the eigendecomposition formula for a matrix. If the matrix is real symmetric, how will this change?
Is the Eigendecomposition guaranteed to be unique? If not, then how do we represent it?
What are positive definite, negative definite, positive semi definite and negative semi definite matrices?
What is Singular Value Decomposition? Why do we use it? Why not just use ED?
Given a matrix A, how will you calculate its Singular Value Decomposition?
What are singular values, left singulars and right singulars?
What is the connection of Singular Value Decomposition of A with functions of A?
Why are singular values always non-negative?
What is the Moore Penrose pseudo inverse and how to calculate it?
If we do Moore Penrose pseudo inverse on Ax = b, what solution is provided is A is fat? Moreover, what solution is provided if A is tall?
Which matrices can be decomposed by ED?
Which matrices can be decomposed by SVD?
What is the trace of a matrix?
How to write Frobenius norm of a matrix A in terms of trace?
Why is trace of a multiplication of matrices invariant to cyclic permutations?
What is the trace of a scalar?
Write the frobenius norm of a matrix in terms of trace?